### ISSUE TITLE
ValueError: no field of name time. when processing ldopa dataset

### ISSUE THREAD

**Issue by farazBhatti** [OxWearables/ssl-wearables#23]
I am getting ValueError: no field of name time, when processing ldopa dataset. using ldopa.py.
Has anyone used ldopa.py for processing ?

```
Traceback (most recent call last):
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/faraz/Desktop/PhD/Generic-Model/ssl-wearables/data_parsing/ldopa.py", line 558, in load_and_make_windows
    load_data(datafile, **PROCESS_ARGS["load_data_args"]),
  File "/home/faraz/Desktop/PhD/Generic-Model/ssl-wearables/data_parsing/ldopa.py", line 425, in load_data
    data, _ = actipy.process(data, sample_rate, verbose=False)
  File "/home/faraz/.local/lib/python3.10/site-packages/actipy/reader.py", line 141, in process
    data, info_lowpass = P.lowpass(data, sample_rate, lowpass_hz)
  File "/home/faraz/.local/lib/python3.10/site-packages/actipy/processing.py", line 158, in lowpass
    data = mmap2df(data_mmap, copy=True)
  File "/home/faraz/.local/lib/python3.10/site-packages/actipy/processing.py", line 603, in mmap2df
    index=pd.Index(np.asarray(data_mmap[index_col]), name=index_col, copy=copy),
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/memmap.py", line 335, in __getitem__
    res = super().__getitem__(index)
ValueError: no field of name time
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/faraz/Desktop/PhD/Generic-Model/ssl-wearables/data_parsing/ldopa.py", line 596, in <module>
    load_all_and_make_windows(
  File "/home/faraz/Desktop/PhD/Generic-Model/ssl-wearables/data_parsing/ldopa.py", line 533, in load_all_and_make_windows
    *Parallel(n_jobs=n_jobs)(
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
  File "/home/faraz/.local/lib/python3.10/site-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
ValueError: no field of name time
Load all and make windows:  68%|██████████▊     | 19/28 [00:18<00:08,  1.02it/s]
```

Its probably  a bug i guess in actipy.

**Comment by farazBhatti** [comment]
@aidanacquah @angerhang 
In the file actipy/processing.py, I changed 'time' to 'timestamp' on line 619. As there is no column name 'time', ldopa files, rather 'timestamp'. And the code works. Ive now generated npy files for training. Maybe this is the issue.
 But i am not sure if it will work or not as  no config file is given for ldopa dataset.  

From this
def mmap2df(dat```
a_mmap, index_col='time', copy=True):
    """ Convert a numpy structured array to pandas dataframe. """
    columns = [c for c in data_mmap.dtype.names if c != index_col]
    data = pd.DataFrame(
        {c: np.asarray(data_mmap[c]) for c in columns}, copy=copy,
        index=pd.Index(np.asarray(data_mmap[index_col]), name=index_col, copy=copy),
    )
    return data
```

to this

```
def mmap2df(data_mmap, index_col='timestamp', copy=True):
    """ Convert a numpy structured array to pandas dataframe. """
    columns = [c for c in data_mmap.dtype.names if c != index_col]
    data = pd.DataFrame(
        {c: np.asarray(data_mmap[c]) for c in columns}, copy=copy,
        index=pd.Index(np.asarray(data_mmap[index_col]), name=index_col, copy=copy),
    )
    return data
```

**Comment by angerhang** [comment]
This has also been addressed :D
